# Generated by Django 3.2.11 on 2022-02-27 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itemsDB', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amulet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.amulet', verbose_name='Амулет')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('belt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.belt', verbose_name='Пояс')),
                ('boots', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.boots', verbose_name='Ботинки')),
                ('chest_armor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.chestarmor', verbose_name='Нагрудная броня')),
                ('gloves', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.gloves', verbose_name='Перчатки')),
                ('helmet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.helmet', verbose_name='Шлем')),
                ('medal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.medal', verbose_name='Медаль')),
                ('pants', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.pants', verbose_name='Поножи')),
                ('relic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.relic', verbose_name='Реликвия')),
                ('ring_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='itemsDB.ring', verbose_name='Левое кольцо')),
                ('ring_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='itemsDB.ring', verbose_name='Правое кольцо')),
                ('shoulder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.shoulder', verbose_name='Наплечник')),
                ('weapon_left', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.axe', verbose_name='Левая рука')),
                ('weapon_right', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='itemsDB.shield', verbose_name='Правая рука')),
            ],
        ),
    ]
