# Generated by Django 3.2.9 on 2022-02-28 07:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('point_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50)], verbose_name='Points')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('master_class_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='calculate.masterclass', verbose_name='Мастерство 1')),
                ('master_class_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='calculate.masterclass', verbose_name='Мастерство 2')),
            ],
            options={
                'verbose_name': 'Мастерство',
                'verbose_name_plural': 'Мастерства',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='person',
            name='mastery_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.mastery', verbose_name='Мастерство'),
        ),
    ]
