# Generated by Django 3.2.9 on 2022-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_auto_20220228_1012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AddField(
            model_name='person',
            name='at_create',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создание'),
        ),
    ]
