# Generated by Django 3.2.11 on 2022-02-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_auto_20220228_1132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['at_create'], 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
    ]
