# Generated by Django 3.2.11 on 2022-02-22 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='История')),
                ('type', models.CharField(max_length=255, verbose_name='Тип предмета')),
                ('equip_type', models.CharField(max_length=255, verbose_name='Категория')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет предмета')),
                ('base_stat', models.TextField(blank=True, null=True, verbose_name='Базовые характеристики')),
                ('skill_params', models.TextField(blank=True, null=True, verbose_name='Дополнительные характеристики')),
                ('set_name', models.CharField(max_length=255, null=True, verbose_name='Название комплекта')),
                ('set_parts', models.TextField(blank=True, null=True, verbose_name='Части комплекта')),
                ('access_condition', models.TextField(blank=True, null=True, verbose_name='Условия доступа')),
                ('dlc_name', models.CharField(max_length=255, null=True, verbose_name='Название дополнения')),
                ('image', models.TextField(blank=True, null=True, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['color', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Amulet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Амулет',
                'verbose_name_plural': 'Амулеты',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Augment',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Присыпка',
                'verbose_name_plural': 'Присыпки',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Топор',
                'verbose_name_plural': 'Топоры',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Axe2h',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Двуручный топор',
                'verbose_name_plural': 'Двуручные топоры',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Пояс',
                'verbose_name_plural': 'Пояса',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Boots',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Ботинки',
                'verbose_name_plural': 'Ботинки',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='ChestArmor',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Нагрудная броня',
                'verbose_name_plural': 'Нагрудная броня',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Components',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Компонент',
                'verbose_name_plural': 'Компоненты',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Dagger',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Кинжал',
                'verbose_name_plural': 'Кинжалы',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Gloves',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Перчатки',
                'verbose_name_plural': 'Перчатки',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Helmet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Шлем',
                'verbose_name_plural': 'Шлемы',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Mace',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Булава',
                'verbose_name_plural': 'Булавы',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Mace2h',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Двуручная булава',
                'verbose_name_plural': 'Двуручные булавы',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Медаль',
                'verbose_name_plural': 'Медали',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Offhand',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Pants',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Штаны',
                'verbose_name_plural': 'Штаны',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Ranged',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Пистолет',
                'verbose_name_plural': 'Пистолеты',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Ranged2h',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Ружье',
                'verbose_name_plural': 'Ружья',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Реликвия',
                'verbose_name_plural': 'Реликвии',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Ring',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Кольцо',
                'verbose_name_plural': 'Кольца',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Scepter',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Скипетр',
                'verbose_name_plural': 'Скипетры',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Щит',
                'verbose_name_plural': 'Щиты',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Shoulder',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Наплечник',
                'verbose_name_plural': 'Наплечники',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Меч',
                'verbose_name_plural': 'Мечи',
            },
            bases=('itemsDB.item',),
        ),
        migrations.CreateModel(
            name='Sword2h',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itemsDB.item')),
            ],
            options={
                'verbose_name': 'Двуручный меч',
                'verbose_name_plural': 'Двуручные мечи',
            },
            bases=('itemsDB.item',),
        ),
    ]
